export type ExifTagDefinition = {
  type: 'text' | 'number' | 'datetime-local'
  description?: string
}

export type ExifSectionDefinition = Record<string, ExifTagDefinition>

export const addableExifTags: Record<string, ExifSectionDefinition> = {
  Image: {
    ImageWidth: { type: 'number' },
    ImageLength: { type: 'number' },
    BitsPerSample: { type: 'text', description: 'e.g., 8, 8, 8' },
    Make: { type: 'text' },
    Model: { type: 'text' },
    Orientation: { type: 'number' },
    XResolution: { type: 'number' },
    YResolution: { type: 'number' },
    ResolutionUnit: { type: 'number', description: '2 for inches, 3 for cm' },
    Software: { type: 'text' },
    DateTime: { type: 'datetime-local' },
    Artist: { type: 'text' },
    YCbCrPositioning: { type: 'number' },
    Copyright: { type: 'text' },
    HostComputer: { type: 'text' },
    ImageDescription: { type: 'text' },
  },
  Exif: {
    ExposureTime: { type: 'number', description: 'In seconds' },
    FNumber: { type: 'number' },
    ExposureProgram: { type: 'number' },
    ISOSpeedRatings: { type: 'number' },
    SensitivityType: { type: 'number' },
    DateTimeOriginal: { type: 'datetime-local' },
    DateTimeDigitized: { type: 'datetime-local' },
    OffsetTime: { type: 'text', description: 'e.g., +08:00' },
    OffsetTimeOriginal: { type: 'text', description: 'e.g., +08:00' },
    OffsetTimeDigitized: { type: 'text', description: 'e.g., +08:00' },
    CompressedBitsPerPixel: { type: 'number' },
    ShutterSpeedValue: { type: 'number' },
    ApertureValue: { type: 'number' },
    BrightnessValue: { type: 'number' },
    ExposureBiasValue: { type: 'number' },
    MaxApertureValue: { type: 'number' },
    MeteringMode: { type: 'number' },
    LightSource: { type: 'number' },
    Flash: { type: 'number' },
    FocalLength: { type: 'number' },
    UserComment: { type: 'text' },
    ColorSpace: { type: 'number' },
    PixelXDimension: { type: 'number' },
    PixelYDimension: { type: 'number' },
    FocalPlaneXResolution: { type: 'number' },
    FocalPlaneYResolution: { type: 'number' },
    FocalPlaneResolutionUnit: { type: 'number' },
    SensingMethod: { type: 'number' },
    CustomRendered: { type: 'number' },
    ExposureMode: { type: 'number' },
    WhiteBalance: { type: 'number' },
    FocalLengthIn35mmFilm: { type: 'number' },
    SceneCaptureType: { type: 'number' },
    Sharpness: { type: 'number' },
    SubjectDistanceRange: { type: 'number' },
    BodySerialNumber: { type: 'text' },
    LensSpecification: { type: 'text', description: 'e.g., 50, 50, 1.4, 1.4' },
    LensMake: { type: 'text' },
    LensModel: { type: 'text' },
    LensSerialNumber: { type: 'text' },
  },
  GPS: {
    GPSVersionID: { type: 'text', description: 'e.g., 2, 3, 0, 0' },
    GPSLatitudeRef: { type: 'text', description: 'N or S' },
    GPSLatitude: { type: 'text', description: 'e.g., 30, 45, 50.008' },
    GPSLongitudeRef: { type: 'text', description: 'E or W' },
    GPSLongitude: { type: 'text', description: 'e.g., 120, 44, 22.733' },
    GPSAltitudeRef: {
      type: 'number',
      description: '0 for above sea level, 1 for below',
    },
    GPSAltitude: { type: 'number' },
    GPSTimeStamp: { type: 'text', description: 'e.g., 8, 12, 42' },
    GPSSpeedRef: { type: 'text', description: 'K, M, or N' },
    GPSSpeed: { type: 'number' },
    GPSMapDatum: { type: 'text', description: 'e.g., WGS-84' },
    GPSDateStamp: { type: 'text', description: 'YYYY:MM:DD' },
  },
  Interoperability: {
    InteroperabilityIndex: { type: 'text', description: 'e.g., R98' },
  },
}
