export const exifTagMap: Record<string, string> = {
  // Sections
  '0th': 'Image',
  '1st': 'Thumbnail',
  IFD0: 'Image',
  IFD1: 'Thumbnail',
  Exif: 'Exif',
  GPS: 'GPS',
  Interop: 'Interoperability',
  General: 'General',

  // Image
  ImageWidth: 'Image Width',
  ImageHeight: 'Image Height',
  BitsPerSample: 'Bits Per Sample',
  Compression: 'Compression',
  PhotometricInterpretation: 'Photometric Interpretation',
  Orientation: 'Orientation',
  SamplesPerPixel: 'Samples Per Pixel',
  PlanarConfiguration: 'Planar Configuration',
  YCbCrSubSampling: 'YCbCr Sub Sampling',
  YCbCrPositioning: 'YCbCr Positioning',
  XResolution: 'X Resolution',
  YResolution: 'Y Resolution',
  ResolutionUnit: 'Resolution Unit',
  StripOffsets: 'Strip Offsets',
  RowsPerStrip: 'Rows Per Strip',
  StripByteCounts: 'Strip Byte Counts',
  JPEGInterchangeFormat: 'JPEG Interchange Format',
  JPEGInterchangeFormatLength: 'JPEG Interchange Format Length',
  TransferFunction: 'Transfer Function',
  WhitePoint: 'White Point',
  PrimaryChromaticities: 'Primary Chromaticities',
  YCbCrCoefficients: 'YCbCr Coefficients',
  ReferenceBlackWhite: 'Reference Black White',
  DateTime: 'Date Time',
  ImageDescription: 'Image Description',
  Make: 'Make',
  Model: 'Model',
  Software: 'Software',
  Artist: 'Artist',
  Copyright: 'Copyright',

  // Exif
  ExposureTime: 'Exposure Time',
  FNumber: 'FNumber',
  ExposureProgram: 'Exposure Program',
  SpectralSensitivity: 'Spectral Sensitivity',
  ISOSpeedRatings: 'ISO Speed Ratings',
  OECF: 'OECF',
  ExifVersion: 'Exif Version',
  DateTimeOriginal: 'Date Time Original',
  DateTimeDigitized: 'Date Time Digitized',
  ComponentsConfiguration: 'Components Configuration',
  CompressedBitsPerPixel: 'Compressed Bits Per Pixel',
  ShutterSpeedValue: 'Shutter Speed Value',
  ApertureValue: 'Aperture Value',
  BrightnessValue: 'Brightness Value',
  ExposureBiasValue: 'Exposure Bias Value',
  MaxApertureValue: 'Max Aperture Value',
  SubjectDistance: 'Subject Distance',
  MeteringMode: 'Metering Mode',
  LightSource: 'Light Source',
  Flash: 'Flash',
  FocalLength: 'Focal Length',
  SubjectArea: 'Subject Area',
  MakerNote: 'Maker Note',
  UserComment: 'User Comment',
  SubSecTime: 'Sub Sec Time',
  SubSecTimeOriginal: 'Sub Sec Time Original',
  SubSecTimeDigitized: 'Sub Sec Time Digitized',
  FlashpixVersion: 'Flashpix Version',
  ColorSpace: 'Color Space',
  PixelXDimension: 'Pixel X Dimension',
  PixelYDimension: 'Pixel Y Dimension',
  RelatedSoundFile: 'Related Sound File',
  FlashEnergy: 'Flash Energy',
  SpatialFrequencyResponse: 'Spatial Frequency Response',
  FocalPlaneXResolution: 'Focal Plane X Resolution',
  FocalPlaneYResolution: 'Focal Plane Y Resolution',
  FocalPlaneResolutionUnit: 'Focal Plane Resolution Unit',
  SubjectLocation: 'Subject Location',
  ExposureIndex: 'Exposure Index',
  SensingMethod: 'Sensing Method',
  FileSource: 'File Source',
  SceneType: 'Scene Type',
  CFAPattern: 'CFA Pattern',
  CustomRendered: 'Custom Rendered',
  ExposureMode: 'Exposure Mode',
  WhiteBalance: 'White Balance',
  DigitalZoomRatio: 'Digital Zoom Ratio',
  FocalLengthIn35mmFilm: 'Focal Length In 35mm Film',
  SceneCaptureType: 'Scene Capture Type',
  GainControl: 'Gain Control',
  Contrast: 'Contrast',
  Saturation: 'Saturation',
  Sharpness: 'Sharpness',
  DeviceSettingDescription: 'Device Setting Description',
  SubjectDistanceRange: 'Subject Distance Range',
  ImageUniqueID: 'Image Unique ID',
  CameraOwnerName: 'Camera Owner Name',
  BodySerialNumber: 'Body Serial Number',
  LensSpecification: 'Lens Specification',
  LensMake: 'Lens Make',
  LensModel: 'Lens Model',
  LensSerialNumber: 'Lens Serial Number',
  Gamma: 'Gamma',

  // GPS
  GPSVersionID: 'GPS Version ID',
  GPSLatitudeRef: 'GPS Latitude Ref',
  GPSLatitude: 'GPS Latitude',
  GPSLongitudeRef: 'GPS Longitude Ref',
  GPSLongitude: 'GPS Longitude',
  GPSAltitudeRef: 'GPS Altitude Ref',
  GPSAltitude: 'GPS Altitude',
  GPSTimeStamp: 'GPS TimeStamp',
  GPSSatellites: 'GPS Satellites',
  GPSStatus: 'GPS Status',
  GPSMeasureMode: 'GPS Measure Mode',
  GPSDOP: 'GPS DOP',
  GPSSpeedRef: 'GPS Speed Ref',
  GPSSpeed: 'GPS Speed',
  GPSTrackRef: 'GPS Track Ref',
  GPSTrack: 'GPS Track',
  GPSImgDirectionRef: 'GPS Img Direction Ref',
  GPSImgDirection: 'GPS Img Direction',
  GPSMapDatum: 'GPS Map Datum',
  GPSDestLatitudeRef: 'GPS Dest Latitude Ref',
  GPSDestLatitude: 'GPS Dest Latitude',
  GPSDestLongitudeRef: 'GPS Dest Longitude Ref',
  GPSDestLongitude: 'GPS Dest Longitude',
  GPSDestBearingRef: 'GPS Dest Bearing Ref',
  GPSDestBearing: 'GPS Dest Bearing',
  GPSDestDistanceRef: 'GPS Dest Distance Ref',
  GPSDestDistance: 'GPS Dest Distance',
  GPSProcessingMethod: 'GPS Processing Method',
  GPSAreaInformation: 'GPS Area Information',
  GPSDateStamp: 'GPS Date Stamp',
  GPSDifferential: 'GPS Differential',
  GPSHPositioningError: 'GPS HPositioning Error',
}
